import { Inter } from "next/font/google";
import "./globals.css";
import Nav from "./(components)/nav";
import "bootstrap/dist/css/bootstrap.css";
import AuthProvider from "./(components)/authProvider";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <AuthProvider>
        <body className="bg-gray-100">
          <Nav />
          <div className="m-2">{children}</div>
        </body>
      </AuthProvider>
    </html>
  );
}
